name: get_cli_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  google_fonts: ^6.1.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.2
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
  assets: 
    - assets/icon/icon.png
    - assets/images/Product1.jpg
    - assets/icon/Upload_Image_Default.png
  uses-material-design: true

